matrix:
  include:
  - language: node_js
    node_js:
    - '10'
    before_install:
    - cd frontend/foodbook
    install:
    - yarn install # use either npm or yarn
    script:
    - ./node_modules/.bin/eslint src
    - yarn test --coverage --watchAll=false
  - language: python
    python:
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"
    before_install:
    - cd backend/foodbook
    install:
    - pip install -r requirements.txt
    script:
    - pylint --load-plugins pylint_django */models.py */views/*.py */tests/*.py
    - python manage.py makemigrations
    - python manage.py migrate
    - coverage run --branch --source='./foodbook_api' manage.py test foodbook_api/tests/
    - coverage report -m
