# Generated by Django 2.2.4 on 2019-10-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodbook_api', '0004_auto_20191028_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.CharField(max_length=120),
        ),
    ]
